server:
  port: ${port:9091}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.itheima.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    #更倾向使用ip地址，而不是host名 ，如果刚更换这个配置第一次访问可能还是host名，再访问一次或者再重启一次或者等一等就好了
    #注意 ：这里改的不是服务注册到eureka的名称，而是消费者调用服务获取实例时的host
    prefer-ip-address: true
    #ip地址
    ip-address: 127.0.0.1
    #续约间隔，默认30秒
    lease-renewal-interval-in-seconds: 5
    #服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
    #ip-address: 127.0.0.9
    #ip-address: 127.0.1.9
    #ip-address: 127.1.1.9
    #ip-address: 128.1.1.9
test:
  name: heima
